server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://96.45.189.113:3306/leyou?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 96.45.189.113
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: K:/JetBrains/rsa/id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
    appID: wx8397f8696b538317
    mchID: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    httpConnectTimeoutMs: 1000
    httpReadTimeoutMs: 8000
    tradeType: NATIVE
    spbillCreateIp: localhost
    notifyUrl: http://pj7t76.natappfree.cc/wxpay/notify