server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    master:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/leyou
      username: root
      password: 123
    slave:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/leyou-slave
      username: root
      password: 123
  redis:
    host: 192.168.206.103
  rabbitmq:
    host: 192.168.206.103
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  type-aliases-package: com.leyou.item.pojo