server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://96.45.189.113:3306/leyou?characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
  redis:
    host: 96.45.189.113
  rabbitmq:
    host: 96.45.189.113
    username: smilepet
    password: smilepet
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
mybatis:
  type-aliases-package: com.leyou.item.pojo