server:
  port: 8083
spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 96.45.189.113:9300
  rabbitmq:
    host: 96.45.189.113
    username: smilepet
    password: smilepet
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka