server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
ly:
  jwt:
    secret: ly@Login(Auth}*^36)&leYou36%f3q124jflaf2 # 登录校验的密钥
    pubKeyPath: K:/JetBrains/rsa/id_rsa.pub # 公钥地址
    priKeyPath: K:/JetBrains/rsa/id_rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN