server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
    host: 96.45.189.113
    username: smilepet
    password: smilepet
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
ly:
  page:
    destPath: K:/nginx-1.12.2/html/item