server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
  sensitive-headers:
  add-host-header: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 熔断超时时长：5000ms
ribbon: #负载均衡
  ConnectTimeout: 1000  #连接超时
  ReadTimeout: 3500  #服务器读取到可用资源超时
ly:
  jwt:
    pubKeyPath: K:/JetBrains/rsa/id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/send
      - /api/item